controllers/DefaultController.php
<?php

namespace quoma\media\controllers;

use quoma\core\web\Controller;
use quoma\media\models\Media;
use quoma\media\models\MediaSearch;
use quoma\modules\config\models\Config;
use Yii;
use yii\filters\VerbFilter;
use yii\web\NotFoundHttpException;
use quoma\media\components\helpers\MediaFactory;

class DefaultController extends Controller
{
    
    public $embedLayout = 'embed';
 
    public function behaviors()
    {
        if (count(\quoma\media\MediaModule::getInstance()->defaultControllerBehaviors) === 0) {
            return [
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['post'],
                    ],
                ],
            ];
        }else{
            return \quoma\media\MediaModule::getInstance()->defaultControllerBehaviors;
        }
        
    }
    
    /**
     * Lists all Image models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MediaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    
    /**
     * Finds the Image model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Image the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Media::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    
    public function actionGetMedia($id)
    {
        \Yii::$app->response->format= \yii\web\Response::FORMAT_JSON;
        
        $media = \quoma\media\models\Media::findOne($id);
        $media->scenario= 'insert-cont';
        
        return [
            'status' => 'success',
            'media' => $media->render(850),
            'epigraph_param' => Config::getValue('insert_image_epigraph') && $media->type == 'Image',
            'include_epigraph' => $media->hasCaption()
        ];
    }
    
    /**
     * Permite buscar en la biblioteca multimedia
     * @return json
     */
    public function actionSearch()
    { 
        
        Yii::$app->response->format= \yii\web\Response::FORMAT_JSON;
        
        if(Yii::$app->request->get('types', false)){
            $showTypes = strip_tags(Yii::$app->request->get('types'));
            $showTypes = explode(',',$showTypes);
        }else{
            $showTypes = MediaFactory::getNames();
        }
        
        $searchModel = new MediaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return [
            'status' => 'success',
            'form' => $this->renderAjax('search', ['showTypes' => $showTypes, 'searchModel' => $searchModel, 'dataProvider' => $dataProvider]),
            'title' => Yii::t('app', 'Search'),
            'pages' => [
                'pageCount' => $dataProvider->pagination->pageCount,
                'totalCount' => $dataProvider->pagination->totalCount,
                'currentPage' => $dataProvider->pagination->page + 1
            ]
       ];
    }
    
    /**
     * Permite renderizar una preview de un recurso multimedia
     * @param int $media_id
     * @return json
     */
    public function actionPreview($media_id)
    {
        
        $media = Media::findOne($media_id);
        
        Yii::$app->response->format= \yii\web\Response::FORMAT_JSON;
        
        return [
            'status' => 'success',
            'media' => $media,
            'preview' => $this->preview($media)
        ];
    }
    
    /**
     * Permite renderizar una preview de un recurso multimedia con las caracteristicas
     * por defecto definidas en el modulo
     * @param type $model
     * @return type
     */
    protected function preview($model)
    {
        $defaultPreviewOptions = \quoma\media\MediaModule::getInstance()->defaultPreviewOptions;
        
        //Si el widget especifica opciones de previsualización
        $previewOptions = \yii\helpers\Json::decode(Yii::$app->request->post('previewOptions', '{}'));
        
        return \quoma\media\components\view\Preview::widget(array_merge([
            'update' => true,
            'media' => $model,
        ], array_merge($defaultPreviewOptions, $previewOptions)));
    }
    
    /**
     * Renderiza la grilla de resultados de búsqueda multimedia
     * @return json
     */
    public function actionMediaGrid()
    {
        
        $searchModel = new MediaSearch();
        $mediaQuery = $searchModel->search(Yii::$app->request->queryParams);
        $count= clone $mediaQuery;
        $pages= new \yii\data\Pagination(['totalCount' => $count->count(), 'pageSize' => 16]);
        
        $dataMedia= $mediaQuery->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
        $data=[];
        
        foreach ($dataMedia as $media) {
            $data[] = \quoma\media\components\helpers\MediaFactory::getMediaObject($media);
        }
                
        Yii::$app->response->format= \yii\web\Response::FORMAT_JSON;
        
        return [
            'status' => 'success',
            'form' => $this->renderAjax('media_grid', ['pages' => $pages, 'media' => $data, 'searchModel' => $searchModel]),
            'totalPages' => $pages->pageCount,
        ];
    }
    
    /**
     * Renderiza la vista de un media especifico
     * @param type $id
     * @return type
     */
    public function actionView($id){
        $model = Media::findOne($id);
        
        $viewFile = \yii\helpers\Inflector::camel2id($model->type).'/view.php';
        if(file_exists(__DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'views'.DIRECTORY_SEPARATOR.$viewFile)){
            return $this->redirect([\yii\helpers\Inflector::camel2id($model->type).'/view', 'id' => $id]);
        }
        
        return $this->render('view', ['model' => $model]);
    }
    
    public function actionCreate()
    {
        return $this->render('create');
    }
    
    
    public function actionDelete($id){
        $model= Media::findOne($id);        
        
        if($model->delete()){
            Yii::$app->session->addFlash('success', Yii::t('app', 'Media deleted successfull'));
        }else{
            Yii::$app->session->addFlash('error', Yii::t('app', 'Can`t be delete the media element'));
            
        }
        
        return $this->redirect(['index']);
    }
    
    /**
     * Permite actualizar los datos de los modelos desde la pantalla de alta de media.
     */
    public function actionUpdateAll()
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        
        $success = true;
        $errors = [];
        
        $mediaData = Yii::$app->request->post('MediaData');
        if(is_array($mediaData)){
            
            foreach($mediaData as $key => $data){
                $model = Media::findOne($key);
                if($model){
                    $success = $this->saveModelData($model, $data) && $success;
                    
                    if($model->hasErrors()){
                        $errors[] = $model->getErrorsAsString();
                    }
                }
            }
            
        }
        
        if($success === true){
            return [
                'status' => 'success',
                'message' => 'Data saved.'
            ];
        }else{
            return [
                'status' => 'error',
                'message' => Yii::t('app', 'Error.').' '.implode(' ', $errors)
            ];
        }
    }
    
    /**
     * Guarda los datos de cada recurso media
     * @param Media $model
     * @param array $data
     */
    private function saveModelData($model, $data){
        
        foreach($data as $attr => $val){
            $model->$attr = $val;
        }

        return $model->save(true);
        
    }
}

controllers/ImageController.php
<?php

namespace quoma\media\controllers;

use Yii;
use quoma\media\models\types\Image;
use quoma\media\models\types\search\ImageSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\base\DynamicModel;

/**
 * ImageController implements the CRUD actions for Image model.
 */
class ImageController extends DefaultController
{
    
    /**
     * @inheritdoc
     */
    public function beforeAction($action)
    {            
        if ($action->id == 'ckupload') {
            $this->enableCsrfValidation = false;
        }

        return parent::beforeAction($action);
    }

    /**
     * Displays a single Image model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Image model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        
        $model = new Image();
        $model->load(Yii::$app->request->post('Media'));
        
        if (Yii::$app->request->isPost && $model->upload()) {
            
            if($model->save()){
                
                return [
                    'status' => 'success',
                    'model' => $model,
                    'preview' => $this->preview($model)
                ];
            }
            
        } 
            
        return [
            'status' => 'error',
            'errors' => $model->getErrors(),
        ];
            
    }
    
       
    /**
     * For CKeditor
     */
    public function actionCkupload(){

        $model = new Image();
        $model->load(Yii::$app->request->post());
        
        if (Yii::$app->request->isPost && $model->upload('upload')) {
            
            if($model->save()){
                return $this->render('_ck-upload', ['model' => $model]);
            }
        }

    }

    /**
     * Updates an existing Image model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->media_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }
    
    /**
     * Inica el proceso de optimización. Si la imagen ya se encuentra optimizada,
     * muestra una preview.
     * @param int $id
     */
    public function actionStartOptimization($id)
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $model = $this->findModel($id);
        
        if($model->isOptimized()){
            
            $steps = \quoma\media\models\types\Image::getAspects();
        
            return [
                'status' => 'success',
                'form' => $this->renderPartial('optimization-preview', [
                    'model' => $model,
                    'steps' => $steps
                ]),
                'errors' => $model->getErrors(),
                'title' => Yii::t('app', 'Image aspect optimization preview')
            ];
        }
        
        return $this->actionOptimize($id);
    }
    
    /**
     * Permite optimizar una imagen para distintas relaciones de aspecto.
     * El step 0 se utiliza para mostrar una preview cdo la imagen ya está
     * optimizada. A partir del step 1, se accede a los steps
     * @param integer $id
     * @return mixed
     */
    public function actionOptimize($id, $step = 0)
    {
        
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        
        $model = $this->findModel($id);
        
        $steps = \quoma\media\models\types\Image::getAspects();
        
        if (isset($_POST['x1']) && $step >=0) {

            $x1 = Yii::$app->request->post('x1');
            $x2 = Yii::$app->request->post('x2');
            $y1 = Yii::$app->request->post('y1');
            $y2 = Yii::$app->request->post('y2');
            
            $validationModel = DynamicModel::validateData(compact('x1', 'x2', 'y1', 'y2'), [
                [['x1', 'x2', 'y1', 'y2'], 'double', 'max' => 100, 'min' => 0],
                [['x1'], 'compare', 'compareValue' => $x2, 'operator' => '<', 'type' => 'number'],
                [['y1'], 'compare', 'compareValue' => $y2, 'operator' => '<', 'type' => 'number'],
            ]);

            if ($validationModel->hasErrors()) {
                throw new \yii\web\HttpException(500, 'Bad data.');
            } 
            
            //Ancho y alto de la nueva imagen
            $newWidth = (int)((($x2 - $x1)/100) * $model->sourceWidth );
            $newHeight = (int)((($y2 - $y1)/100) * $model->sourceHeight );
            
            $start = [ (int)(($x1/100)*$model->sourceWidth), (int)(($y1/100)*$model->sourceHeight) ];
            
            //marcar las imagenes previas como inválidas borrando el tamaño (no borrar porque puede estar en cache la url)
            $model->invalidate($newWidth, $newHeight);
            
            $cropped = $model->crop($newWidth, $newHeight, $start);

            if($cropped !== false){
                if(isset($steps[$step+1])){
                    ++$step;
                }else{
                    return [
                        'status' => 'success',
                        'step' => -1,
                        'media_id' => $model->media_id,
                        'label' => '<span class="glyphicon glyphicon-phone"></span> ' . Yii::t('app','Optimized')
                    ];
                }
            }else{
                return [
                    'status' => 'error',
                    'errors' => Yii::t('app', 'Image could not be cropped.')
                ];
            }
            
        } 
        
        return [
            'status' => 'success',
            'step' => $step,
            'form' => $this->renderPartial('optimize', [
                'model' => $model,
                'step' => $step,
                'steps' => $steps
            ]),
            'errors' => $model->getErrors(),
            'title' => Yii::t('app', 'Image aspect optimization')
        ];
    }

    /**
     * Deletes an existing Image model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

}

views/image/_button.php
<?= 
\common\modules\media\components\upload\UploadWidget::widget(['media' => $media, 'type' => 'image', 'label' => Yii::t('app', 'Images')]); 
?>

views/image/_ck-upload.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CKEditor upload</title>
</head>
<body>
<?php
// Required: anonymous function reference number as explained above.
$funcNum = $_GET['CKEditorFuncNum'] ;
// Optional: instance name (might be used to load a specific configuration file or anything else).
$CKEditor = $_GET['CKEditor'] ;

// Check the $_FILES array and save the file. Assign the correct path to a variable ($url).
$url = $model->url;

echo "<script type='text/javascript'>window.parent.CKEDITOR.tools.callFunction($funcNum, '$url');</script>";
?>
</body>
</html>

views/image/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\media\models\types\Image */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="image-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => 140]) ?>

    <?= $form->field($model, 'description')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'status')->dropDownList([ 'enabled' => 'Enabled', 'disabled' => 'Disabled', ]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/image/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\modules\media\models\types\search\ImageSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="image-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'media_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'base_url') ?>

    <?php // echo $form->field($model, 'relative_url') ?>

    <?php // echo $form->field($model, 'type') ?>

    <?php // echo $form->field($model, 'mime') ?>

    <?php // echo $form->field($model, 'size') ?>

    <?php // echo $form->field($model, 'width') ?>

    <?php // echo $form->field($model, 'height') ?>

    <?php // echo $form->field($model, 'extension') ?>

    <?php // echo $form->field($model, 'create_date') ?>

    <?php // echo $form->field($model, 'create_time') ?>

    <?php // echo $form->field($model, 'create_timestamp') ?>

    <?php // echo $form->field($model, 'status') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('app', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/image/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\modules\media\models\types\Image */

$this->title = Yii::t('app', 'Create Image');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Images'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="image-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/image/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\media\models\types\search\ImageSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Images');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="image-index">

    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>
    </div>
    
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a(Yii::t('app', 'Create Image'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'media_id',
            'title',
            'description',
            'name',
            'base_url:url',
            // 'relative_url:url',
            // 'type',
            // 'mime',
            // 'size',
            // 'width',
            // 'height',
            // 'extension',
            // 'create_date',
            // 'create_time',
            // 'create_timestamp:datetime',
            // 'status',

            ['class' => 'backend\components\ActionColumn'],
        ],
    ]); ?>

</div>

views/image/optimization-preview.php
<div class="image-optimize">
    <div class="row">
        <div class="col-sm-12" style="text-align: center;">
            
            <div class="col-sm-12">
                <?php 
                
                $colMdWidth = count($steps) < 3 ? 6 : 4;
                
                foreach($steps as $stepNumber => $step):
                    $width = $step['minWidth'];
                    $height = $width / $step['aspect'];
                    ?>
                
                    <div class="col-xs-6 col-md-<?= $colMdWidth ?>">
                        <a href="#" data-media-action data-media-url="<?= yii\helpers\Url::to(['/media/image/optimize', 'id' => $model->media_id, 'step' => $stepNumber]) ?>" class="thumbnail">
                        <?= yii\helpers\Html::img($model->getSizedUrl((int)$width, (int)$height));?>
                            <div class="caption">
                                <h3><?= $step['name'] ?></h3>
                                <p><?= Yii::t('app', 'Click to edit') ?></p>
                            </div>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr/>
        </div>
        <div class="col-sm-9">
            <a data-popover data-trigger="focus" data-placement="top" tabindex="0" class="btn" role="button" title="<?= Yii::t('app', 'Help') ?>" 
               data-content="En esta pantalla usted puede visualizar los recortes previamente generados. Puede optar
               por actualizar un recorte o todos."><span class="glyphicon glyphicon-question-sign"></span> <?= Yii::t('app', 'Need help?') ?></a>
        </div>
        <div class="col-sm-3">
            <a data-media-action href="#Cut" class="btn btn-primary pull-right" data-media-url="<?= yii\helpers\Url::to(['/media/image/optimize', 'id' => $model->media_id, 'step' => 0]) ?>">
                <?= Yii::t('app', 'Optimize again').' <span class="glyphicon glyphicon-arrow-right"></span>' ?>
            </a>
        </div>
    </div>
</div>

views/image/optimize.php
<?php 
$lastStep = ($step == (count($steps)-1)) ? true : false;
?>

<div class="image-optimize">
    <div class="row">
        <div class="col-sm-12" style="text-align: center;">
            
            <div class="row bs-wizard" style="border-bottom:0;">
                
                <?php foreach($steps as $stepNumber => $stepData): 
                    
                    $stepClass = 'disabled';
                    if($stepNumber == $step){
                        $stepClass = 'active';
                    }elseif($stepNumber < $step){
                        $stepClass = 'complete';
                    }
                    ?>
                <div class="col-xs-<?= (int)(12/count($steps)) ?> bs-wizard-step <?= $stepClass ?>">
                    <div class="text-center bs-wizard-stepnum"><?= $stepData['name'] ?></div>
                    <div class="progress"><div class="progress-bar"></div></div>
                    <a href="#" class="bs-wizard-dot"></a>
                    <div class="bs-wizard-info text-center"><?= Yii::t('app', 'Step {number}', ['number'=>$stepNumber+1]) ?></div>
                </div>
                <?php endforeach; ?>
                 
            </div>
            
            <?php 
            /**
            <ol class="carousel-indicators optimize-indicators pull-right">
                <?php foreach($steps as $stepNumber => $stepData): ?>
                <li data-step="<?= $stepNumber ?>" class="<?= ($stepNumber == $step) ? 'active' : '' ?>"><?= $stepData['name'] ?></li>
                <?php endforeach; ?>
            </ol>
            */
            ?>
            
            <div class="col-sm-12">
                <div class="optimizer-container" style="position:relative; overflow: hidden; display: inline-block;" 
                     data-min-width="<?= $steps[$step]['minWidth'] ?>" 
                     data-min-height="<?= $steps[$step]['minHeight'] ?>"
                     data-aspect="<?= $steps[$step]['aspect'] ?>">
                    <div data-cutter style="position:absolute; z-index: 100000; cursor: move;"></div>
                    <img id="img2optimize" src="<?= $model->url ?>" style="max-width: 100%;" />
                </div>
            </div>

        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr/>
        </div>
        <div class="col-sm-9">
            <a data-popover data-trigger="focus" data-placement="top" tabindex="0" class="btn" role="button" title="<?= Yii::t('app', 'Help') ?>" 
               data-content="Con esta herramienta usted podrá optimizar el tamaño y las proporciones de las imagenes, para que se vean bien en todo el sitio y 
               desde cualquier dispositivo. Para esto, ubique el costado o la esquina del rectángulo de corte (si no lo visualiza, 
               es posible que coincida con el borde de la imagen). Podrá mover, ampliar y reducir el rectángulo de corte hasta ver 
               la porción de imagen adecuada. Luego presione 'Siguiente' o 'Finalizar'. Repita estos pasos para todos los tamaños
               de imagen solicitados."><span class="glyphicon glyphicon-question-sign"></span> <?= Yii::t('app', 'Need help?') ?></a>
        </div>
        <div class="col-sm-3">
            <div class="pull-right">
                <?php if($model->isOptimized()): ?>
                    <?php if($lastStep): ?>
                    <a href="#Skip" class="btn btn-default" onclick="Media.close()">
                        <?= '<span class="glyphicon glyphicon-remove-sign"></span> '.Yii::t('app', 'Skip') ?>
                    </a>
                    <?php else: ?>
                    <a href="#Skip" class="btn btn-default" data-media-action data-media-url="<?= yii\helpers\Url::to(['/media/image/optimize','id'=>$model->media_id,'step' => $lastStep ? -1 : ($step+1)]) ?>">
                        <?= '<span class="glyphicon glyphicon-remove-sign"></span> '.Yii::t('app', 'Skip') ?>
                    </a>
                    <?php endif; ?>

                <?php endif; ?>
                <a data-optimize-send href="#Cut" class="btn btn-primary" data-url="<?= yii\helpers\Url::to(['/media/image/optimize', 'id' => $model->media_id, 'step' => $step]) ?>">
                    <?= $lastStep ? '<span class="glyphicon glyphicon-check"></span> '.Yii::t('app', 'Finish') : Yii::t('app', 'Next').' <span class="glyphicon glyphicon-arrow-right"></span>' ?>
                </a>
            </div>
        </div>
    </div>
</div>
<script>
ImageOptimizer.init();
</script>

views/image/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\modules\media\models\types\Image */

$this->title = Yii::t('app', 'Update {modelClass}: ', [
    'modelClass' => 'Image',
]) . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Images'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->media_id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="image-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/image/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model backend\modules\media\models\types\Image */

$this->title = $model->title ? $model->title : $model->type;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Media'), 'url' => ['default/index']];
$this->params['breadcrumbs'][] = $this->title;

$this->registerCss('.img-container{ 
        max-width: 100%; 
        max-height: 100%;
        overflow: hidden;
    } 
    .img-container img{
        margin: 10px;
        max-width: 100%;
        max-height: 100%;
    }
    .cut-preview{
        height: 400px;
    }
    .img-container.center{
        text-align: center;
    }
    @-moz-document url-prefix() {
        img { width: 100%; max-width: -moz-max-content; }
    }
    @media (min-width: 1024px){
        .main-container{
            height: 600px;
            margin-bottom: 20px;
        }
    }
'
);

quoma\media\components\widgets\ButtonsAssets::register($this);
$this->registerJs('Media.init({editorSelector: "", previewOptions: {}});');

quoma\media\components\image\OptimizerAssets::register($this);
?>
<div class="image-view">

    <div class="title">
        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->media_id], ['class' => 'btn btn-primary']) ?>
            <?php if($model->deletable) echo Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->media_id], [
                'class' => 'btn btn-danger',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                    'method' => 'post',
                ],
            ]) ?>
            <?= ' ' . $model->customButtons(); ?>
        </p>
    </div>

    <div class="row">
        <div class="col-md-6">
            <div class="img-container center main-container">
            <?php echo $model->render()?>
            </div>
        </div>
        <div class="col-sm-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'media_id',
                    'title',
                    'description',
                    'name',
                    'url:url',
                    'relative_url:url',
                    'type',
                    'mime',
                    'size:shortSize',
                    'width',
                    'height',
                    'extension',
                    'create_date',
                    'create_time',
                    'create_timestamp:datetime',
                    'status',
                ],
            ]) ?>
        </div>
    </div>
    
    <?php if(count($model->sizeds) > 0):?>
    
    <h2><?php echo Yii::t('app', 'Cuts')?></h2>
    <hr/>
    
    <div class="row">
        <?php 
        foreach ($model->sizeds as $sized):?>
            <div class="col-lg-6">
                <h3><?= Yii::t('app','Width: {w}px', ['w' => $sized->width]) ?> | <?= Yii::t('app','Height: {h}px', ['h' => $sized->height]) ?></h3>
                <pre><?= $model->getSizedUrl($sized->width, $sized->height) ?></pre>
                <div class="img-container cut-preview">
                    <?php echo $model->render($sized->width, $sized->height)?>
                </div>
                <hr/>
            </div>
        <?php endforeach;?>
    </div>
    
    <?php endif; ?>

</div>